services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports: 
      - 6379:6379
    networks:
      - app_network  # Connect to the same network as the Redis service
  redisinsight:
    image: redis/redisinsight:latest  # Use the RedisInsight image
    container_name: redis_insight  # Optional: name your RedisInsight container
    ports:
      - "8001:8001"  # Map RedisInsight web UI port
    depends_on:
      - redis
    networks:
      - app_network  # Connect to the same network as the Redis service
# volumes:
#   pgdata:
#   mongodata:

networks:
  app_network:  # Define a custom network to allow the services to communicate
    driver: bridge